#!/usr/bin/env python3
"""Reproduce the H=5, iteration-30 magnitude vector-field snapshot.

This script imports the self-contained convergence-behaviour runner,
replays the H=5 magnitude-optimized recovery run up to iteration 30,
and writes

1. a PNG preview figure using Matplotlib, and
2. a TikZ/PGFPlots snippet that visually follows the Matplotlib snapshot.

The TikZ version uses PGFPlots 3-D axes, separate PGF/TikZ arrows, small
arrowheads, a non-overlapping legend, and the same qualitative camera/view as
Matplotlib's elev=24, azim=-48.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "reproduce_convergence_behaviour.py"

# Visual constants used by both the TikZ and PNG exports.
DECISION_ARROW_SCALE = 0.13
OBJECTIVE_ARROW_SCALE = 0.085
TIKZ_ARROW_HEAD = "Latex[length=0.75mm,width=0.60mm]"
TIKZ_VIEW = "315}{24"  # PGFPlots view={azimuth}{elevation}, chosen to mimic matplotlib azim=-48,elev=24.


def load_algorithm_module(src: Path):
    spec = importlib.util.spec_from_file_location("conv_alg", src)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def run_snapshot(iteration: int = 30, H: int = 5, seed: int = 0):
    alg = load_algorithm_module(SOURCE)
    # Keep the visualization run deterministic and independent of numba cache details.
    alg.NUMBA_AVAILABLE = False
    recovery_kwargs = dict(
        max_iter=iteration,
        alpha0=0.020,
        eps_layer=1e-3,
        tau=5e-4,
        sigma=0.060,
        shrink=0.65,
        max_retries=6,
        alpha_boost=1.00,
        stagnation_window=10,
        stagnation_tol=5.0e-3,
        stochastic_step=0.160,
        stochastic_trials=3,
        stochastic_seed=31,
        perturb_fraction=0.45,
        perturb_cooldown=10,
        max_backtrack_drop=0.12,
        final_unperturbed_iters=10,
        indicator="magnitude",
    )
    res = alg.run_projected_ascent_with_stochastic_recovery(
        alg.supersphere_box_h_budget_initial_points(H=H, seed=seed),
        alg.supersphere_gamma1_box_objective,
        alg.supersphere_gamma1_jacobian,
        alg.project_3d_layered_box,
        **recovery_kwargs,
    )
    X = np.asarray(res["hist_X"][iteration], dtype=float)
    Y = np.asarray(res["hist_Y"][iteration], dtype=float)
    value, GY, layers = alg.layered_value_and_gradient(
        Y,
        eps_layer=recovery_kwargs["eps_layer"],
        tau=recovery_kwargs["tau"],
        sigma=recovery_kwargs["sigma"],
        indicator="magnitude",
    )
    J = alg.supersphere_gamma1_jacobian(X)
    GX = np.einsum("nij,ni->nj", J, GY)
    GX = alg.normalize_rows(GX)
    GY_dir = alg.normalize_rows(GY)
    return alg, res, X, Y, GX, GY_dir, value, layers


def coords_block(arr: np.ndarray) -> str:
    return " ".join(f"({p[0]:.6f},{p[1]:.6f},{p[2]:.6f})" for p in arr)


def tikz_arrow_draws(P: np.ndarray, D: np.ndarray, scale: float, color: str = "blue!70!black") -> str:
    lines = []
    for p, d in zip(P, D):
        q = p + scale * d
        lines.append(
            rf"\draw[-{{{TIKZ_ARROW_HEAD}}}, {color}, line width=0.24pt, opacity=0.88] "
            rf"(axis cs:{p[0]:.6f},{p[1]:.6f},{p[2]:.6f}) -- "
            rf"(axis cs:{q[0]:.6f},{q[1]:.6f},{q[2]:.6f});"
        )
    return "\n".join(lines)


def layer_indices(n: int, layers: list[list[int]]) -> tuple[np.ndarray, np.ndarray]:
    layer_of = np.empty(n, dtype=int)
    for ell, front in enumerate(layers):
        for idx in front:
            layer_of[idx] = ell
    idx1 = np.where(layer_of == 0)[0]
    idx2 = np.where(layer_of == 1)[0]
    return idx1, idx2


def generate_tikz(path: Path, alg, X, Y, GX, GY, layers, value, iteration: int = 30, H: int = 5):
    idx1, idx2 = layer_indices(len(X), layers)
    grid = alg.das_dennis_simplex_grid_3d(20)
    grid_y = alg.supersphere_gamma1_box_objective(grid)

    mins = np.minimum(Y.min(axis=0), grid_y.min(axis=0))
    maxs = np.maximum(Y.max(axis=0), grid_y.max(axis=0))
    pad = 0.08 * np.maximum(maxs - mins, 1e-9)
    obj_min = mins - pad
    obj_max = maxs + pad
    simplex = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]])

    text = rf"""% Automatically generated by reproduce_h5_iteration30_magnitude_vectorfield.py
% H=5, iteration {iteration}, magnitude indicator.  TikZ/PGFPlots version tuned
% to match the Matplotlib snapshot: view, arrow scale, small arrowheads, and legend placement.
\begin{{tikzpicture}}
\pgfplotsset{{
  vectorfield axis/.style={{
    width=0.48\linewidth,
    height=0.60\linewidth,
    view={{{TIKZ_VIEW}}},
    tick label style={{font=\scriptsize}},
    label style={{font=\scriptsize}},
    title style={{font=\small, yshift=-0.5ex}},
    grid=major,
    grid style={{gray!30}},
    axis background/.style={{fill=gray!4}},
    axis lines=box,
    clip=false,
    every axis plot/.append style={{line join=round}},
  }}
}}
\begin{{axis}}[
  vectorfield axis,
  name=decaxis,
  at={{(0cm,0cm)}},
  xlabel={{$x_1$}}, ylabel={{$x_2$}}, zlabel={{$x_3$}},
  title={{Decision space: projected ascent}},
  xmin=-0.45,xmax=1.45,
  ymin=-0.45,ymax=1.45,
  zmin=-0.45,zmax=1.45,
  xtick={{-0.25,0,0.5,1.0,1.25}},
  ytick={{-0.25,0,0.5,1.0,1.25}},
  ztick={{-0.25,0,0.5,1.0,1.25}},
]
\addplot3[densely dashed, gray!75, line width=0.45pt] coordinates {{{coords_block(simplex)}}};
\addplot3[only marks, mark=*, mark size=1.70pt, blue!72!black] coordinates {{{coords_block(X[idx1])}}};
\addplot3[only marks, mark=triangle*, mark size=1.95pt, orange!90!black] coordinates {{{coords_block(X[idx2])}}};
{tikz_arrow_draws(X, GX, DECISION_ARROW_SCALE)}
\end{{axis}}
\begin{{axis}}[
  vectorfield axis,
  at={{(0.55\linewidth,0cm)}},
  anchor=south west,
  xlabel={{$f_1$}}, ylabel={{$f_2$}}, zlabel={{$f_3$}},
  title={{Objective space: magnitude gradient}},
  xmin={obj_min[0]:.6f}, xmax={obj_max[0]:.6f},
  ymin={obj_min[1]:.6f}, ymax={obj_max[1]:.6f},
  zmin={obj_min[2]:.6f}, zmax={obj_max[2]:.6f},
]
\addplot3[only marks, mark=*, mark size=0.38pt, blue!45, opacity=0.16] coordinates {{{coords_block(grid_y)}}};
\addplot3[only marks, mark=*, mark size=1.70pt, blue!72!black] coordinates {{{coords_block(Y[idx1])}}};
\addplot3[only marks, mark=triangle*, mark size=1.95pt, orange!90!black] coordinates {{{coords_block(Y[idx2])}}};
{tikz_arrow_draws(Y, GY, OBJECTIVE_ARROW_SCALE)}
\end{{axis}}
\end{{tikzpicture}}
"""
    path.write_text(text, encoding="utf-8")


def generate_png(path: Path, alg, X, Y, GX, GY, layers, value, iteration: int = 30, H: int = 5):
    idx1, idx2 = layer_indices(len(X), layers)
    layer_of = np.zeros(len(X), dtype=int)
    for ell, front in enumerate(layers):
        for idx in front:
            layer_of[idx] = ell
    markers = ["o", "^", "s", "D"]

    fig = plt.figure(figsize=(13.5, 6.5), dpi=170)
    ax_dec = fig.add_subplot(1, 2, 1, projection="3d")
    ax_obj = fig.add_subplot(1, 2, 2, projection="3d")

    simplex_vertices = np.array([[1.0, 0.0, 0.0],[0.0, 1.0, 0.0],[0.0, 0.0, 1.0],[1.0, 0.0, 0.0]])
    ax_dec.plot(simplex_vertices[:, 0], simplex_vertices[:, 1], simplex_vertices[:, 2], linestyle="--", linewidth=1.0)

    grid = alg.das_dennis_simplex_grid_3d(20)
    grid_y = alg.supersphere_gamma1_box_objective(grid)
    ax_obj.scatter(grid_y[:, 0], grid_y[:, 1], grid_y[:, 2], s=5, alpha=0.12)

    for ell in range(len(layers)):
        idx = np.where(layer_of == ell)[0]
        marker = markers[ell % len(markers)]
        label = f"Layer {ell+1} ({len(idx)})"
        ax_dec.scatter(X[idx, 0], X[idx, 1], X[idx, 2], s=28, marker=marker, label=label)
        ax_obj.scatter(Y[idx, 0], Y[idx, 1], Y[idx, 2], s=28, marker=marker, label=label)

    ax_dec.quiver(X[:, 0], X[:, 1], X[:, 2], GX[:, 0], GX[:, 1], GX[:, 2], length=DECISION_ARROW_SCALE, normalize=False, linewidth=0.8, arrow_length_ratio=0.22)
    ax_obj.quiver(Y[:, 0], Y[:, 1], Y[:, 2], GY[:, 0], GY[:, 1], GY[:, 2], length=OBJECTIVE_ARROW_SCALE, normalize=False, linewidth=0.8, arrow_length_ratio=0.22)

    ax_dec.set_title("Decision space: projected magnitude ascent directions")
    ax_obj.set_title("Objective space: magnitude-gradient directions")
    ax_dec.set_xlabel(r"$x_1$")
    ax_dec.set_ylabel(r"$x_2$")
    ax_dec.set_zlabel(r"$x_3$")
    ax_obj.set_xlabel(r"$f_1$")
    ax_obj.set_ylabel(r"$f_2$")
    ax_obj.set_zlabel(r"$f_3$")
    ax_dec.set_xlim(-0.45, 1.45)
    ax_dec.set_ylim(-0.45, 1.45)
    ax_dec.set_zlim(-0.45, 1.45)
    mins = np.minimum(Y.min(axis=0), grid_y.min(axis=0))
    maxs = np.maximum(Y.max(axis=0), grid_y.max(axis=0))
    pad = 0.08 * np.maximum(maxs - mins, 1e-9)
    ax_obj.set_xlim(mins[0] - pad[0], maxs[0] + pad[0])
    ax_obj.set_ylim(mins[1] - pad[1], maxs[1] + pad[1])
    ax_obj.set_zlim(mins[2] - pad[2], maxs[2] + pad[2])
    ax_dec.view_init(elev=24, azim=-48)
    ax_obj.view_init(elev=24, azim=-48)
    for ax in (ax_dec, ax_obj):
        ax.grid(True)
        try:
            ax.set_box_aspect((1,1,1))
        except Exception:
            pass
    fig.suptitle(f"H=5, magnitude indicator, iteration {iteration}; mu={len(X)}, layered value={value:.6f}, layers=" + "+".join(str(len(layer)) for layer in layers), y=0.98)
    ax_dec.legend(loc="lower left", frameon=True, fontsize=8)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def write_standalone(path: Path, snippet_path: Path):
    path.write_text(
        r"""\documentclass[tikz,border=4pt]{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usetikzlibrary{arrows.meta,calc,patterns,positioning}
\usepackage{xcolor}
\begin{document}
""" + snippet_path.read_text(encoding="utf-8") + "\n\\end{document}\n",
        encoding="utf-8",
    )


def main():
    alg, _res, X, Y, GX, GY, value, layers = run_snapshot(iteration=30, H=5, seed=0)
    tikz_path = ROOT / "h5_iteration30_magnitude_vectorfield.tikz.tex"
    standalone_path = ROOT / "h5_iteration30_magnitude_vectorfield_standalone.tex"
    png_path = ROOT / "h5_iteration30_magnitude_vectorfield_snapshot.png"
    generate_tikz(tikz_path, alg, X, Y, GX, GY, layers, value, iteration=30, H=5)
    write_standalone(standalone_path, tikz_path)
    generate_png(png_path, alg, X, Y, GX, GY, layers, value, iteration=30, H=5)
    print(f"Wrote {tikz_path}")
    print(f"Wrote {standalone_path}")
    print(f"Wrote {png_path}")


if __name__ == "__main__":
    main()
